# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d4a16436a96a88898bb591eae2c63589a352356bac2cb7abffa248f8f374a8cc5abbf0a55a87428ba78a365091bd3e9cf3bf4d0c22ba185fe9b7931f48dcd4f

test:
  secret_key_base: 6c1f81897ed6a773778a31150e6289dab3691119089c70dfac1ba4314f3136f6558116ff76a1b83764395888f4b8a4fd93ce9d7d450b1b5d750f466e55bb4b4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
